### ISSUE TITLE
TypeError: initial_value must be str or None, not bytes

### ISSUE THREAD

**Issue by qq0r** [mattgwwalker/msg-extractor#75] opened 2019-03-04 09:39 UTC
In order to get your bug addressed in a timely manner, or at all :smiley:, please fill out the below bug report. Please try to make it as easy as possible for us to understand what is going on. We may close out any bugs or issues without warning that are not complete or coherent.

In the bug template below anything is [square brackets] should be filled out or removed if the item doesn't apply.

Should you encounter an error that has not already been reported, please do the following when reporting it:
**Bug Metadata**
* - [X] Using latest supported version of extract_msg
* Your python version: Python [2.7 | 3.6.7]
* How did you launch extract_msg?
  - [ ] My command line or
  - [X] I used the extract_msg package

**Describe the bug**
I am trying to extract attachments from a .msg file, but get the following error: 
"AttributeError: 'Message' object has no attribute '_header'
(...)
During handling of the above exception, another exception occurred:
(...)
TypeError: initial_value must be str or None, not bytes"

[ If applicable ]
**What code did you use or can we use to reproduce this error?

```
msg = extract_msg.Message("abc.msg")
```

Is there a message.msg file you want to share to help us reproduce this?
- [ ] Uploaded message (drag and drop on this window)
- [ ] Emailed message as an attachment to admins: [Enter Subject Line Here]

**Traceback**
```
Traceback (most recent call last)
<ipython-input-11-998a469fed84> in <module>()
----> 1 msg = extract_msg.Message("abc.msg")

~\AppData\Local\Continuum\anaconda3\lib\site-packages\extract_msg\message.py in __init__(self, path, prefix, attachmentClass, filename)
     83         # lines will be unnecessary.
     84         self.mainProperties
---> 85         self.header
     86         self.recipients
     87         self.attachments

~\AppData\Local\Continuum\anaconda3\lib\site-packages\extract_msg\message.py in header(self)
    222             headerText = self._getStringStream('__substg1.0_007D')
    223             if headerText is not None:
--> 224                 self._header = EmailParser().parsestr(headerText)
    225                 self._header['date'] = self.date
    226             else:

~\AppData\Local\Continuum\anaconda3\lib\email\parser.py in parsestr(self, text, headersonly)
     66         the file.
     67         """
---> 68         return self.parse(StringIO(text), headersonly=headersonly)
     69 
     70 

TypeError: initial_value must be str or None, not bytes

```

**Screenshots**
[Insert any screenshots or debug pictures here]

**Additional context**
[Add any other context about the problem here.]

**Comment by qq0r** [comment] 2019-03-04 09:43
Is it possible for me to use your package (msg-extractor) to extract attachments from .msg files that do not have a header? Crossing fingers, and thanks in advance!

**Comment by TheElementalOfCreation** [comment] 2019-03-04 09:48
The problem here is not that the header is missing (as handling for that event already exists and does not raise an error). What I believe happened is that the header is in the file `__substg1.0_007D001E` instead of `__substg1.0_007D001F`. If that is the case, then this is a bug we are currently fixing. The problem is that the header is not properly being converted from bytes to string, and the email module can't handle that.

Please see the specified comment on the following issue, and follow the instructions. Then respond with the results.

https://github.com/mattgwwalker/msg-extractor/issues/71#issuecomment-465203737

**Comment by qq0r** [comment] 2019-03-04 14:45
Thanks for your quick reply. 

I followed the instructions in thread #71: 
import olefile
a = olefile.OleFileIO('abc.msg')
print('Unicode version found: {}'.format(a.exists('__substg1.0_007D001F')))
print('Other version found: {}'.format(a.exists('__substg1.0_007D001E')))

And this is the result:
Unicode version found: False
Other version found: True

So you're right - the header is in file __substg1.0_007D001E ...

**Comment by TheElementalOfCreation** [comment] 2019-04-13 19:50
Okay, so I am FINALLY working on actually fixing this. I... uh... kind of forgot about this issue for a while. Sorry about that. I've found a property of msg files that tells the encoding if it is non-unicode.

Only problem is that it is stored in a way that I don't yet understand. 

I'll let you know when this gets fixed.

**Comment by TheElementalOfCreation** [comment] 2019-04-13 21:44
Oh by the way, you might want to change the thread title to something like "TypeError: initial_value must be str or None, not bytes" as that was the exception that broke everything. The attribute error was in the process of being handled when the TypeError was thrown

**Comment by qq0r** [comment] 2019-04-15 08:41
Thanks for your update! 

I am waiting in excitement for your fix as my current project really can benefit from using your package to extract attachments from .msg files. 

I will change the thread title to your suggestion.

**Comment by TheElementalOfCreation** [comment] 2019-04-18 18:21
A fix for this has been found! We should hopefully have the update pushed within the next few days!

This was not fun to fix, but in the process of fixing this I made a few changes that were a long time coming, so that's a plus.

**Comment by TheElementalOfCreation** [comment] 2019-04-18 18:37
Congrats, this should now be fixed. Lets try to have everyone who has been following this issue confirm that it works for them before we close this. Version 0.23.0 has this fix.

**Comment by Heat-Miser** [comment] 2019-04-19 10:04
Hello,

I tried the last version on my stash of mails and I had this stacktrace

`Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/extract_msg/message.py", line 488, in attachments
    return self._attachments
AttributeError: 'Message' object has no attribute '_attachments'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/extract_msg/message.py", line 303, in areStringsUnicode
    return self.__bStringsUnicode
AttributeError: 'Message' object has no attribute '_Message__bStringsUnicode'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/extract_msg/message.py", line 256, in mainProperties
    return self._prop
AttributeError: 'Message' object has no attribute '_prop'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "mail_hunter.py", line 108, in <module>
    msg = Message(filepath)
  File "/usr/local/lib/python3.7/site-packages/extract_msg/message.py", line 87, in __init__
    self.attachments
  File "/usr/local/lib/python3.7/site-packages/extract_msg/message.py", line 501, in attachments
    self._attachments.append(self.__attachmentClass(self, attachmentDir))
  File "/usr/local/lib/python3.7/site-packages/extract_msg/attachment.py", line 52, in __init__
    self.__data = msg.__class__(self.msg.path, self.__prefix, self.__class__)
  File "/usr/local/lib/python3.7/site-packages/extract_msg/message.py", line 68, in __init__
    filename = self._getStringStream(prefixl[:-1] + ['__substg1.0_3001'], prefix=False)
  File "/usr/local/lib/python3.7/site-packages/extract_msg/message.py", line 160, in _getStringStream
    if self.areStringsUnicode:
  File "/usr/local/lib/python3.7/site-packages/extract_msg/message.py", line 305, in areStringsUnicode
    if self.mainProperties.has_key('340D0003'):
  File "/usr/local/lib/python3.7/site-packages/extract_msg/message.py", line 258, in mainProperties
    self._prop = Properties(self._getStream('__properties_version1.0'),
  File "/usr/local/lib/python3.7/site-packages/extract_msg/message.py", line 145, in _getStream
    filename = self.fix_path(filename, prefix)
  File "/usr/local/lib/python3.7/site-packages/extract_msg/message.py", line 141, in fix_path
    inp = self.__prefix + inp
AttributeError: 'Message' object has no attribute '_Message__prefix'
`

I'm using extract-msg==0.23.0.

Did I do something wrong ?

**Comment by TheElementalOfCreation** [comment] 2019-04-19 10:11
Oh shoot. I'll fix that in the morning. That's my bad. I didn't run tests on recursive emails.

**Comment by Heat-Miser** [comment] 2019-04-19 10:11
👍thx for the really quick feeback !

**Comment by TheElementalOfCreation** [comment] 2019-04-23 19:50
Okay, NOW it should be fixed

**Comment by Heat-Miser** [comment] 2019-05-02 12:39
I finally found some time to test it and it works like a charm ! Thanks a heap for your work ! 👌👍

**Comment by qq0r** [comment] 2019-05-06 14:31
I have also tested your fix, and I agree with Heat-Miser - it works really well! 
Thanks a lot for your effort. It is much appreciated!!

**Comment by GTCrais** [comment] 2020-09-07 08:50
So I ran into this myself. The `AttributeError` exception gets caught, but then another exception is thrown:

```
Traceback (most recent call last):
  File "C:\wamp64\www\_Python\MsgParser\lib\site-packages\extract_msg\message_base.py", line 243, in header
    return self._header
AttributeError: 'Message' object has no attribute '_header'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\wamp64\www\_Python\MsgParser\lib\site-packages\extract_msg\msg.py", line 477, in stringEncoding
    return self.__stringEncoding
AttributeError: 'Message' object has no attribute '_MSGFile__stringEncoding'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/Crais/PyCharmProjects/MsgParser/main.py", line 6, in <module>
    extract_msg.Message('emails/CTL013651.msg')
  File "C:\wamp64\www\_Python\MsgParser\lib\site-packages\extract_msg\message.py", line 28, in __init__
    MessageBase.__init__(self, path, prefix, attachmentClass, filename, delayAttachments, overrideEncoding)
  File "C:\wamp64\www\_Python\MsgParser\lib\site-packages\extract_msg\message_base.py", line 51, in __init__
    self.header
  File "C:\wamp64\www\_Python\MsgParser\lib\site-packages\extract_msg\message_base.py", line 245, in header
    headerText = self._getStringStream('__substg1.0_007D')
  File "C:\wamp64\www\_Python\MsgParser\lib\site-packages\extract_msg\msg.py", line 162, in _getStringStream
    return None if tmp is None else tmp.decode(self.stringEncoding)
  File "C:\wamp64\www\_Python\MsgParser\lib\site-packages\extract_msg\msg.py", line 487, in stringEncoding
    raise MissingEncodingError('Encoding property not found')
extract_msg.exceptions.MissingEncodingError: Encoding property not found
```

**Comment by TheElementalOfDestruction** [comment] 2020-09-07 08:57
@GTCrais that is not a problem with our module. That is a problem with your msg file. If you want, you can attempt to guess the encoding and feed it into the opening of the msg files with the "overrideEncoding" field. So if you think the encoding is "utf-8" you could do ```python
# I personally recommend using the extract_msg.openMsg function, but since you did it this way...
extract_msg.Message('path/to/msgfile.msg', overrideEncoding='utf-8')
```

**Comment by TheElementalOfDestruction** [comment] 2020-09-07 08:57
@GTCrais that is not a problem with our module. That is a problem with your msg file. If you want, you can attempt to guess the encoding and feed it into the opening of the msg files with the "overrideEncoding" field. So if you think the encoding is "utf-8" you could do ```python
# I personally recommend using the extract_msg.openMsg function, but since you did it this way...
extract_msg.Message('path/to/msgfile.msg', overrideEncoding='utf-8')
```

**Closed** 2020-09-07 09:00 UTC
Labels: Fixed?, bug

**Comment by ethannakamura1211** [comment] 2020-09-16 09:55
@TheElementalOfDestruction I seem to be running into a similar problem as @GTCrais 


![Screenshot 2020-09-16 105258](https://user-images.githubusercontent.com/35020565/93322190-f448e200-f80a-11ea-84a0-09bf468de3ce.jpg)

**Comment by GTCrais** [comment] 2020-09-16 10:02
I've attempted various things to work around this, but the issue is actually pretty simple: the .msg files are just incosistent, sometimes "broken" in ways no language or library can understand it.
I also tried parsing .msg files in PHP, to no avail. One *and only* one solution worked consistently with whatever .msg file I threw at it: the `win32com.client` library (https://stackoverflow.com/questions/59707906/how-save-or-extract-attachments-file-from-msg-file-with-python). This will only work on Windows machines with Outlook installed, and the only reason it will work is because it uses actual Outlook to read the emails. In conclusion - Outlook is the only thing that can consistently handle reading .msg files. Don't even bother with anything else because you'll just lose your sanity. Like I did.

**Comment by TheElementalOfDestruction** [comment] 2020-09-16 10:11
Sometimes there are things within the msg file that just don't match the specifications at all and yet somehow still work in outlook. The fact that outlook supports that is a bit ridiculous, but we also support that to an extent. If your file is missing an encoding or has the wrong one listed, you just have to guess what is the correct one. 

I actually have an example email that I have been trying to make work in the module that, according to all the information I could find from Microsoft, is using the wrong encoding, yet outlook somehow knows what it is supposed to be.

You think trying to use our module with broken files is a nightmare? The real nightmares are trying for years to make a module work for broken files and trying to get Microsoft to cough up information about how Outlook works. Thanks, Microsoft.

**Comment by ethannakamura1211** [comment] 2020-09-16 10:23
Thanks. I guess `win32com.client` would actually be the only option then.
