### ISSUE TITLE
AttributeError: 'OSError' object has no attribute 'message' 

### ISSUE THREAD

**Issue by manikanthgoud559** [mattgwwalker/msg-extractor#129] opened 2020-06-20 16:06 UTC
In order to get your bug addressed in a timely manner, or at all :smiley:, please fill out the below bug report. Please try to make it as easy as possible for us to understand what is going on. We may close out any bugs or issues without warning that are not complete or coherent.

In the bug template below anything is [square brackets] should be filled out or removed if the item doesn't apply.

Should you encounter an error that has not already been reported, please do the following when reporting it:
**Bug Metadata**
* - [* ] Using latest supported version of extract_msg
* Your python version: Python [2.7 | 3.6.7]
* How did you launch extract_msg?
  - [ ] My command line or
  - [ *] I used the extract_msg package

**Describe the bug**

[ If applicable ]
**What code did you use or can we use to reproduce this error?

```
[put your code here]
```

Is there a message.msg file you want to share to help us reproduce this?
- [ ] Uploaded message (drag and drop on this window)
- [ ] Emailed message as an attachment to admins: [Enter Subject Line Here]

**Traceback**
```
[Put your traceback here]
```

**Screenshots**
[
![image](https://user-images.githubusercontent.com/27899776/85206198-fdc2cb00-b33d-11ea-9413-4296c28a1f6d.png)
]
![image](https://user-images.githubusercontent.com/27899776/85206205-10d59b00-b33e-11ea-9c6e-036594418f8b.png)

**Additional context**
[Add any other context about the problem here.]

**Comment by TheElementalOfCreation** [comment] 2020-06-20 16:07
What version are you using? This should already be fixed in the most recent one

**Comment by manikanthgoud559** [comment] 2020-06-21 03:21
![image](https://user-images.githubusercontent.com/27899776/85215893-427d4f00-b39c-11ea-8186-eb52088608b6.png)

Currently i am using version : 0.23.3

**Comment by TheElementalOfCreation** [comment] 2020-06-21 03:22
The most recent version is 0.24.3 please upgrade using github.

**Comment by TheElementalOfCreation** [comment] 2020-06-21 21:23
Duplicate of [112](https://github.com/mattgwwalker/msg-extractor/issues/112). Closing.

**Closed by TheElementalOfCreation** 2020-06-21 21:23 UTC
