### ISSUE TITLE
message.cc mail@example.org <None>

### ISSUE THREAD

**Issue by srkunze** [mattgwwalker/msg-extractor#55] opened 2018-11-27 15:38 UTC
I got a message when parsed yielding:

```
>>> message = Message(path)
>>> message.to
mail@example.org <None>

>>> mail_attachment.recipients[0]._Recipient__dir
'__recip_version1.0_#00000000'

>>> mail_attachment.recipients[0]._Recipient__email
None

>>> mail_attachment.recipients[0]._Recipient__formatted
'mail@example.org <None>'

>>> mail_attachment.recipients[0]._Recipient__name
mail@example.org

>>> mail_attachment.recipients[0]._Recipient__type
1
```

**Comment by TheElementalOfCreation** [comment] 2018-11-27 15:45
That is not an error with the program but with the msg file itself, I believe. However, if you would like, you can send the msg file to arceusthe@gmail.com and I will look into it further to see if it actually is a problem with the program.

**Comment by srkunze** [comment] 2018-11-30 14:05
Mhhh, not sure that's 100% correct but email is always messy.

I fixed my immediate problem now by using 

```
def get_msg_addresses(message, header_key):
        for name, mail in AddressList(message.header[header_key]):
            yield decode_header(try_unicode(name)), mail
```

I think there's a more general issue, so I will open a new one.

**Comment by TheElementalOfCreation** [comment] 2018-11-30 22:59
No, seriously. This is an actual internal problem in many msg files. The recipients sometimes have their emails and names switched, or only have a name which is actually the email. They sometimes even only have a name.

One problem with your solution right now is that some msg files are literally completely missing the header, which means that the script has to manually build it from the information it can find.

**Comment by srkunze** [comment] 2018-12-03 10:17
I gather you're talking about the exception block in the cc-property, right?
```
        except Exception:
            # Check header first
            if self.headerInit():
                headerResult = self.header['cc']
                if headerResult is not None:
                    self._cc = headerResult
            else:
                f = []
                for x in self.recipients:
                    if x.type & 0x0000000f == 2:
                        f.append(x.formatted)
                if len(f) > 0:
                    st = f[0]
                    if len(f) > 1:
                        for x in range(1, len(f)):
                            st += '; {0}'.format(f[x])
                    self._cc = st
                else:
                    self._cc = None
            return self._cc
```

So, I see problems here:

1) messed up email and name
2) information not in headers but in "__recip" (coming from the recipient property)


For 1) stlib works (at least in my case).
For 2) you've already have a working solution, it's just the interface doesn't line up with the stdlib's one.

**Comment by TheElementalOfCreation** [comment] 2018-12-03 16:11
Actually,slight correction. You DID run into a bug. Should be fixed in the next update, whenever that is.

**Comment by TheElementalOfCreation** [comment] 2018-12-03 16:19
please use version 0.20.5 and see if the issue is fixed.

**Comment by srkunze** [comment] 2018-12-05 09:46
Give me some time to test it.

About the general issue: I don't necessarily see a contradiction here. I got emails archived as msg files. Surely, there might be some cases where this doesn't hold but this doesn't concern me right now.

What I actually need is the information to display the msg file as if they were an email.

Furthermore, by using the standard stdlib rfc2822.AddressList everything works as expected instead of using the (sender, to, cc) properties exposed by your library. Maybe, I'm missing something but that's actually a hint that it might have some benefit to work with it.

**Comment by srkunze** [comment] 2018-12-05 13:31
Test performed with 0.20.7. <None> is still there:

```
>>> self.message.recipients[0].formatted
mail@example.org <None>

>>> isinstance(self.message.header, dict)
False
```

**Comment by TheElementalOfCreation** [comment] 2018-12-05 13:33
Please check the result of `message.header['cc']`

**Comment by srkunze** [comment] 2018-12-05 14:31
Alright. Different example:

```
>>> message.recipients[0].formatted
FirstName LastName <None>

>>> AddressList(message.header['to'])
('FirstName LastName', 'mail@example.org')

>>> message.header.__str__()
From nobody Wed Dec  5 15:29:01 2018
Return-Path: mail@example.org
Received: from Kueh (Unknown [XX.XX.XX.XX.XX]) by XXXXXXXXX.de with ESMTP
 ; Mon, 15 Oct 2018 15:10:23 +0200
From: <sender@example.org>
To: "FirstName LastName" <mail@example.org>
References: <1391996.39.1539329871.JavaMail.root@strato-web-prod-02.cln.erp>
In-Reply-To: <1391296.4639.129871.JavaMail.root@strato-web-prod-02.cln.erp>
Subject: =?utf-8?Q?WG:_Example=C3=BCr_....?=
Date: Mon, 15 Oct 2018 15:10:33 +0200
Message-ID: <0f1888$74f0$5bfd0$@example.org>
MIME-Version: 1.0
Content-Type: multipart/mixed;
 boundary="----=_NextPart_000_0F19_01D46499.387BFA50"
X-Mailer: Microsoft Outlook 14.0
Thread-Index: AQFT2UbPa1fzUaYhXlAA
Content-Language: de
X-EsetId: A84E33539FA0C6A
date: Mo, 15 Okt 2018 15:10:33 GMT +0200
```

**Comment by TheElementalOfCreation** [comment] 2018-12-05 23:07
Okay, so your message has a header confirmed. This next test will help me figure out exactly why the email is not appearing. Please run the following code and respond with the results. Make sure you have a message instance initialized and stored in the variable `message`. Careful planning has gone into the writing of this test to ensure no private information is exposed.

```
a = []
for x in message.listDir():
    if x[0].startswith('__recip'):
        if x[-1].endswith('001F') or x[-1].endswith('001E'):
            a.append((x, '@' in message._getStream(x).decode('utf_16_le')))
print(a)
```

**Comment by punkrokk** [comment] 2018-12-06 05:34
v0.20.8 has another bug fix

**Comment by TheElementalOfCreation** [comment] 2018-12-09 00:07
Please get back to us as soon as possible so we can try to squash this bug.

**Comment by srkunze** [comment] 2018-12-09 11:38
hey folks, sorry for being absent, I'm ill for the upcoming week, but will definitely come back once I'm better 🤒

**Comment by srkunze** [comment] 2018-12-19 12:03
Alright. That's the output of `mail@example.org <None>`:
```
[(['__recip_version1.0_#00000000', '__substg1.0_3001001F'], False),
 (['__recip_version1.0_#00000000', '__substg1.0_3002001F'], False),
 (['__recip_version1.0_#00000000', '__substg1.0_3003001F'], True),
 (['__recip_version1.0_#00000001', '__substg1.0_3001001F'], True),
 (['__recip_version1.0_#00000001', '__substg1.0_3002001F'], False),
 (['__recip_version1.0_#00000001', '__substg1.0_3003001F'], True)]
```

**Comment by TheElementalOfCreation** [comment] 2018-12-19 17:47
Okay, confirmed issue is with our current handling. Will be fixed in 0.21.0

**Comment by TheElementalOfCreation** [comment] 2018-12-19 17:51
However the recipient name being an email address is NOT our fault for recipient 1:
![image](https://user-images.githubusercontent.com/24580325/50238189-90626280-0373-11e9-853d-82c039820170.png)

**Comment by TheElementalOfCreation** [comment] 2018-12-28 20:17
Version 0.21.0 is out. If your issue is not fixed, please comment and I will reopen it.

**Closed by TheElementalOfCreation** 2018-12-28 20:17 UTC
