### ISSUE TITLE
AttributeError: 'Message' object has no attribute '_header'

### ISSUE THREAD

**Issue by storm42** [mattgwwalker/msg-extractor#79] opened 2019-04-18 12:13 UTC
**Bug Metadata**
- [x] Using latest supported version of extract_msg
- [x] Python version: Python [3.7]
- [x] I used the extract_msg package in PyCharm

**Describe the bug**
While opening a .msg file, I encountered this error :
```
Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\Python\Python37\site-packages\extract_msg\message.py", line 220, in header
    return self._header
AttributeError: 'Message' object has no attribute '_header'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Python\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Program Files (x86)\Python\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "%script_path%\__main__.py", line 3, in <module>
    checkURL.call("C:\\Users\\User\\Downloads\\outlook mail.msg")
  File "%script_path%\scripts\checkURL.py", line 25, in call
    print(extract_msg.Message(l_email_file))
  File "C:\Users\User\AppData\Roaming\Python\Python37\site-packages\extract_msg\message.py", line 85, in __init__
    self.header
  File "C:\Users\User\AppData\Roaming\Python\Python37\site-packages\extract_msg\message.py", line 224, in header
    self._header = EmailParser().parsestr(headerText)
  File "C:\Program Files (x86)\Python\lib\email\parser.py", line 68, in parsestr
    return self.parse(StringIO(text), headersonly=headersonly)
TypeError: initial_value must be str or None, not bytes

Process finished with exit code 1
```

I think there is an handled exception, but one more exception occurs while the other is being catched...
Could you give me any clue ?

Thanks

**Comment by TheElementalOfCreation** [comment] 2019-04-18 13:55
Duplicate of #75

**Closed by TheElementalOfCreation** 2019-04-18 13:55 UTC
